server:
    port: 8002
    error:
        include-message: always
        include-binding-errors: always
        
spring:
    application:
        name: bootcamp-asset
    data:
        mongodb:
            uri: mongodb+srv://root:s3cr3t@bootcampcluster02.pi7tw.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://10.244.0.26:8099/eureka}
    
resilience4j.circuitbreaker:
    instances:
        createAssetCB:
            registerHealthIndicator: true
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowSize: 15
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
            eventConsumerBufferSize: 10
        findAssetCB:
            registerHealthIndicator: true
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowSize: 15
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
            eventConsumerBufferSize: 10
        findAllAssetsCB:
            registerHealthIndicator: true
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowSize: 15
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
            eventConsumerBufferSize: 10
        updateAssetCB:
            registerHealthIndicator: true
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowSize: 15
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
            eventConsumerBufferSize: 10
        deleteAssetCB:
            registerHealthIndicator: true
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowSize: 15
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
            eventConsumerBufferSize: 10
