server:
    port: 8001
    error:
        include-message: always
        include-binding-errors: always
        
spring:
    application:
        name: bootcamp-client
    data:
        mongodb:
            uri: mongodb+srv://root:s3cr3t@bootcampcluster.zfsso.mongodb.net/MongoClients?retryWrites=true&w=majority

eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8099/eureka/
    