server:
    port: 8002
    error:
        include-message: always
        include-binding-errors: always
        
spring:
    application:
        name: bootcamp-asset
    h2:
        console:
            enabled: true
    data:
        mongodb:
            uri: mongodb://host:127.0.0.1/db
            host: localhost
            database: MongoAssets

eureka:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8099/eureka/
    prefer-ip-address: true