server:
    port: 8003
    error:
        include-message: always
        include-binding-errors: always
        
spring:
    application:
        name: bootcamp-account
    h2:
        console:
            enabled: true
    data:
        mongodb:
            uri: mongodb://host:127.0.0.1/db
            host: localhost
            database: MongoAccounts

eureka:
    client:
        hostname: localhost
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8099/eureka/
        