server:
    port: 8001
    error:
        include-message: always
        include-binding-errors: always
        
spring:
    application:
        name: bootcamp-client
    h2:
        console:
            enabled: true
    data:
        mongodb:
            uri: mongodb+srv://root:s3cr3t@bootcampcluster.zfsso.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

eureka:
    instance:
        hostname: 52.226.138.185
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8099/eureka/
    