server:
    port: 8003
    error:
        include-message: always
        include-binding-errors: always
        
spring:
    application:
        name: bootcamp-account
    data:
        mongodb:
            uri: mongodb+srv://root:s3cr3t@bootcampcluster03.oicvz.mongodb.net/MongoAccounts?retryWrites=true&w=majority

eureka:
    instance:
        hostname: 52.226.138.185
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8099/eureka/
        
