server:
  port: 8090

eureka:
  instance:
    hostname: 52.226.138.185
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bootcamp-clients
          uri: lb://bootcamp-clients
          predicates:
            - Path=/clients/**
        - id: bootcamp-accounts
          uri: lb://bootcamp-accounts
          predicates:
            - Path=/accounts/**
        - id: bootcamp-assets
          uri: lb://bootcamp-assets
          predicates:
            - Path=/assets/**