server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bootcamp-clients
          uri: lb://bootcamp-clients
          predicates:
            - Path=/clients/**
        - id: bootcamp-accounts
          uri: lb://bootcamp-accounts
          predicates:
            - Path=/accounts/**
        - id: bootcamp-assets
          uri: lb://bootcamp-assets
          predicates:
            - Path=/assets/**