server:
  port: 8099

eureka:
  instance:
    hostname: 52.226.138.185
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/