server:
  port: 8099

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://52.226.138.185:8099/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 100